import {
  Activity,
  BookOpen,
  Boxes,
  Building2,
  CalendarCheck,
  Code2,
  Cpu,
  DollarSign,
  FileText,
  Filter,
  Globe,
  GraduationCap,
  Landmark,
  Layers,
  LayoutDashboard,
  MapPin,
  MessageSquare,
  PhoneCall,
  Pill,
  Rocket,
  Scissors,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Target,
  TrendingUp,
  Truck,
  UserPlus,
  Users,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

/**
 * Single registry for every icon the editable site content can reference.
 * Content stores an icon *name*, so anything added here becomes available
 * to the admin panel without touching component code.
 */
export const ICONS: Record<string, LucideIcon> = {
  Activity,
  BookOpen,
  Boxes,
  Building2,
  CalendarCheck,
  Code2,
  Cpu,
  DollarSign,
  FileText,
  Filter,
  Globe,
  GraduationCap,
  Landmark,
  Layers,
  LayoutDashboard,
  MapPin,
  MessageSquare,
  PhoneCall,
  Pill,
  Rocket,
  Scissors,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Target,
  TrendingUp,
  Truck,
  UserPlus,
  Users,
  Wallet,
};

export function getIcon(name: string | undefined, fallback: LucideIcon = Sparkles): LucideIcon {
  return (name && ICONS[name]) || fallback;
}
